version: '3.8'

services:
    web:
        image: nginx
        container_name: weather-web
        working_dir: /application
        volumes:
            - ./environment/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/application
        networks:
            - weather-dev
        ports:
            - ${EXTERNAL_WEBSERVER_PORT:-80}:80
        restart: unless-stopped
        depends_on:
            - php

    php:
        build:
            context: environment/dev/php
        container_name: weather-php
        working_dir: /application
        user: ${CURRENT_UID:-1000}
        volumes:
            - .:/application
            - ./environment/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - weather-dev
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: unless-stopped

    node:
        image: node
        container_name: weather-node
        working_dir: /application
        tty: true
        volumes:
            - .:/application
        networks:
            - weather-dev
        ports:
            - ${EXTERNAL_NODE_PORT:-5173}:5173
        restart: unless-stopped

networks:
    weather-dev:
        driver: bridge
